package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   留言信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table leave_comments
 */
@ApiModel(value="cn.tonghua.database.model.LeaveComments")
public class LeaveComments extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id自增主键")
    private Integer id;

    /**
     * Database Column Remarks:
     *   景点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.site_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="siteId景点id")
    private Integer siteId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createTime创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.comments
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="comments留言")
    private String comments;

    /**
     * Database Column Remarks:
     *   备用1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.cf1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf1备用1")
    private String cf1;

    /**
     * Database Column Remarks:
     *   备用2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.cf2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf2备用2")
    private String cf2;

    /**
     * Database Column Remarks:
     *   备用3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_comments.cf3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf3备用3")
    private String cf3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.id
     *
     * @return the value of leave_comments.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.id
     *
     * @param id the value for leave_comments.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.site_id
     *
     * @return the value of leave_comments.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.site_id
     *
     * @param siteId the value for leave_comments.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.create_time
     *
     * @return the value of leave_comments.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.create_time
     *
     * @param createTime the value for leave_comments.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.comments
     *
     * @return the value of leave_comments.comments
     *
     * @mbg.generated
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.comments
     *
     * @param comments the value for leave_comments.comments
     *
     * @mbg.generated
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.cf1
     *
     * @return the value of leave_comments.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.cf1
     *
     * @param cf1 the value for leave_comments.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1 == null ? null : cf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.cf2
     *
     * @return the value of leave_comments.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.cf2
     *
     * @param cf2 the value for leave_comments.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2 == null ? null : cf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_comments.cf3
     *
     * @return the value of leave_comments.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_comments.cf3
     *
     * @param cf3 the value for leave_comments.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3 == null ? null : cf3.trim();
    }
}