package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   问题答案信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question_answer
 */
@ApiModel(value="cn.tonghua.database.model.QuestionAnswer")
public class QuestionAnswer extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id自增主键")
    private Integer id;

    /**
     * Database Column Remarks:
     *   答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.description
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="description答案")
    private String description;

    /**
     * Database Column Remarks:
     *   问题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.question_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="questionId问题id")
    private Integer questionId;

    /**
     * Database Column Remarks:
     *   是否删除（0：已删除，1：未删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.is_del
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="isDel是否删除（0：已删除，1：未删除）")
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createTime创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.mark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="mark备注")
    private String mark;

    /**
     * Database Column Remarks:
     *   备用1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.cf1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf1备用1")
    private String cf1;

    /**
     * Database Column Remarks:
     *   备用2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.cf2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf2备用2")
    private String cf2;

    /**
     * Database Column Remarks:
     *   备用3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.cf3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf3备用3")
    private String cf3;

    /**
     * Database Column Remarks:
     *   答案标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_answer.answer_mark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerMark答案标识")
    private Integer answerMark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.id
     *
     * @return the value of question_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.id
     *
     * @param id the value for question_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.description
     *
     * @return the value of question_answer.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.description
     *
     * @param description the value for question_answer.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.question_id
     *
     * @return the value of question_answer.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.question_id
     *
     * @param questionId the value for question_answer.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.is_del
     *
     * @return the value of question_answer.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.is_del
     *
     * @param isDel the value for question_answer.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.create_time
     *
     * @return the value of question_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.create_time
     *
     * @param createTime the value for question_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.mark
     *
     * @return the value of question_answer.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.mark
     *
     * @param mark the value for question_answer.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.cf1
     *
     * @return the value of question_answer.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.cf1
     *
     * @param cf1 the value for question_answer.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1 == null ? null : cf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.cf2
     *
     * @return the value of question_answer.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.cf2
     *
     * @param cf2 the value for question_answer.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2 == null ? null : cf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.cf3
     *
     * @return the value of question_answer.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.cf3
     *
     * @param cf3 the value for question_answer.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3 == null ? null : cf3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_answer.answer_mark
     *
     * @return the value of question_answer.answer_mark
     *
     * @mbg.generated
     */
    public Integer getAnswerMark() {
        return answerMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_answer.answer_mark
     *
     * @param answerMark the value for question_answer.answer_mark
     *
     * @mbg.generated
     */
    public void setAnswerMark(Integer answerMark) {
        this.answerMark = answerMark;
    }
}