package cn.tonghua.database.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SiteInfoExample extends cn.tonghua.core.model.AbstractDataAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table site_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public SiteInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andStarIsNull() {
            addCriterion("star is null");
            return (Criteria) this;
        }

        public Criteria andStarIsNotNull() {
            addCriterion("star is not null");
            return (Criteria) this;
        }

        public Criteria andStarEqualTo(Integer value) {
            addCriterion("star =", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotEqualTo(Integer value) {
            addCriterion("star <>", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThan(Integer value) {
            addCriterion("star >", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarGreaterThanOrEqualTo(Integer value) {
            addCriterion("star >=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThan(Integer value) {
            addCriterion("star <", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarLessThanOrEqualTo(Integer value) {
            addCriterion("star <=", value, "star");
            return (Criteria) this;
        }

        public Criteria andStarIn(List<Integer> values) {
            addCriterion("star in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotIn(List<Integer> values) {
            addCriterion("star not in", values, "star");
            return (Criteria) this;
        }

        public Criteria andStarBetween(Integer value1, Integer value2) {
            addCriterion("star between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andStarNotBetween(Integer value1, Integer value2) {
            addCriterion("star not between", value1, value2, "star");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeIsNull() {
            addCriterion("upda_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeIsNotNull() {
            addCriterion("upda_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeEqualTo(Date value) {
            addCriterion("upda_time =", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeNotEqualTo(Date value) {
            addCriterion("upda_time <>", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeGreaterThan(Date value) {
            addCriterion("upda_time >", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("upda_time >=", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeLessThan(Date value) {
            addCriterion("upda_time <", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeLessThanOrEqualTo(Date value) {
            addCriterion("upda_time <=", value, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeIn(List<Date> values) {
            addCriterion("upda_time in", values, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeNotIn(List<Date> values) {
            addCriterion("upda_time not in", values, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeBetween(Date value1, Date value2) {
            addCriterion("upda_time between", value1, value2, "updaTime");
            return (Criteria) this;
        }

        public Criteria andUpdaTimeNotBetween(Date value1, Date value2) {
            addCriterion("upda_time not between", value1, value2, "updaTime");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(String value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(String value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(String value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(String value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(String value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(String value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLike(String value) {
            addCriterion("mark like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotLike(String value) {
            addCriterion("mark not like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<String> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<String> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(String value1, String value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(String value1, String value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andCf1IsNull() {
            addCriterion("cf1 is null");
            return (Criteria) this;
        }

        public Criteria andCf1IsNotNull() {
            addCriterion("cf1 is not null");
            return (Criteria) this;
        }

        public Criteria andCf1EqualTo(String value) {
            addCriterion("cf1 =", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotEqualTo(String value) {
            addCriterion("cf1 <>", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1GreaterThan(String value) {
            addCriterion("cf1 >", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1GreaterThanOrEqualTo(String value) {
            addCriterion("cf1 >=", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1LessThan(String value) {
            addCriterion("cf1 <", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1LessThanOrEqualTo(String value) {
            addCriterion("cf1 <=", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1Like(String value) {
            addCriterion("cf1 like", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotLike(String value) {
            addCriterion("cf1 not like", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1In(List<String> values) {
            addCriterion("cf1 in", values, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotIn(List<String> values) {
            addCriterion("cf1 not in", values, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1Between(String value1, String value2) {
            addCriterion("cf1 between", value1, value2, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotBetween(String value1, String value2) {
            addCriterion("cf1 not between", value1, value2, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf2IsNull() {
            addCriterion("cf2 is null");
            return (Criteria) this;
        }

        public Criteria andCf2IsNotNull() {
            addCriterion("cf2 is not null");
            return (Criteria) this;
        }

        public Criteria andCf2EqualTo(String value) {
            addCriterion("cf2 =", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotEqualTo(String value) {
            addCriterion("cf2 <>", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2GreaterThan(String value) {
            addCriterion("cf2 >", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2GreaterThanOrEqualTo(String value) {
            addCriterion("cf2 >=", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2LessThan(String value) {
            addCriterion("cf2 <", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2LessThanOrEqualTo(String value) {
            addCriterion("cf2 <=", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2Like(String value) {
            addCriterion("cf2 like", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotLike(String value) {
            addCriterion("cf2 not like", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2In(List<String> values) {
            addCriterion("cf2 in", values, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotIn(List<String> values) {
            addCriterion("cf2 not in", values, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2Between(String value1, String value2) {
            addCriterion("cf2 between", value1, value2, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotBetween(String value1, String value2) {
            addCriterion("cf2 not between", value1, value2, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf3IsNull() {
            addCriterion("cf3 is null");
            return (Criteria) this;
        }

        public Criteria andCf3IsNotNull() {
            addCriterion("cf3 is not null");
            return (Criteria) this;
        }

        public Criteria andCf3EqualTo(String value) {
            addCriterion("cf3 =", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotEqualTo(String value) {
            addCriterion("cf3 <>", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3GreaterThan(String value) {
            addCriterion("cf3 >", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3GreaterThanOrEqualTo(String value) {
            addCriterion("cf3 >=", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3LessThan(String value) {
            addCriterion("cf3 <", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3LessThanOrEqualTo(String value) {
            addCriterion("cf3 <=", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3Like(String value) {
            addCriterion("cf3 like", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotLike(String value) {
            addCriterion("cf3 not like", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3In(List<String> values) {
            addCriterion("cf3 in", values, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotIn(List<String> values) {
            addCriterion("cf3 not in", values, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3Between(String value1, String value2) {
            addCriterion("cf3 between", value1, value2, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotBetween(String value1, String value2) {
            addCriterion("cf3 not between", value1, value2, "cf3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table site_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}