package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   景点问题表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table site_question
 */
@ApiModel(value="cn.tonghua.database.model.SiteQuestion")
public class SiteQuestion extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id自增主键")
    private Integer id;

    /**
     * Database Column Remarks:
     *   问题描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.description
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="description问题描述")
    private String description;

    /**
     * Database Column Remarks:
     *   景点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.site_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="siteId景点id")
    private Integer siteId;

    /**
     * Database Column Remarks:
     *   是否删除（0：删除，1：未删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.is_del
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="isDel是否删除（0：删除，1：未删除）")
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createTime创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.mark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="mark备注")
    private String mark;

    /**
     * Database Column Remarks:
     *   备用1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.cf1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf1备用1")
    private String cf1;

    /**
     * Database Column Remarks:
     *   备用2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.cf2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf2备用2")
    private String cf2;

    /**
     * Database Column Remarks:
     *   备用3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_question.cf3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf3备用3")
    private String cf3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.id
     *
     * @return the value of site_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.id
     *
     * @param id the value for site_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.description
     *
     * @return the value of site_question.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.description
     *
     * @param description the value for site_question.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.site_id
     *
     * @return the value of site_question.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.site_id
     *
     * @param siteId the value for site_question.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.is_del
     *
     * @return the value of site_question.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.is_del
     *
     * @param isDel the value for site_question.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.create_time
     *
     * @return the value of site_question.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.create_time
     *
     * @param createTime the value for site_question.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.mark
     *
     * @return the value of site_question.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.mark
     *
     * @param mark the value for site_question.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.cf1
     *
     * @return the value of site_question.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.cf1
     *
     * @param cf1 the value for site_question.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1 == null ? null : cf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.cf2
     *
     * @return the value of site_question.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.cf2
     *
     * @param cf2 the value for site_question.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2 == null ? null : cf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_question.cf3
     *
     * @return the value of site_question.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_question.cf3
     *
     * @param cf3 the value for site_question.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3 == null ? null : cf3.trim();
    }
}