package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   景点信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table site_info
 */
@ApiModel(value="cn.tonghua.database.model.SiteInfo")
public class SiteInfo extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id自增主键")
    private Integer id;

    /**
     * Database Column Remarks:
     *   文件名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="景点名称")
    private String name;

    /**
     * Database Column Remarks:
     *   是否删除（0：删除，1：未删除）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.count
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="点赞数量")
    private Integer count;

    /**
     * Database Column Remarks:
     *   是否启用（0：已启用，1：未启用）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.star
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="星星数")
    private Integer star;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.upda_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="更新时间")
    private Date updaTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.mark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="备注")
    private String mark;

    /**
     * Database Column Remarks:
     *   备用1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.cf1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf1备用1")
    private String cf1;

    /**
     * Database Column Remarks:
     *   备用2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.cf2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf2备用2")
    private String cf2;

    /**
     * Database Column Remarks:
     *   备用3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column site_info.cf3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf3备用3")
    private String cf3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.id
     *
     * @return the value of site_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.id
     *
     * @param id the value for site_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.name
     *
     * @return the value of site_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.name
     *
     * @param name the value for site_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.count
     *
     * @return the value of site_info.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.count
     *
     * @param count the value for site_info.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.star
     *
     * @return the value of site_info.star
     *
     * @mbg.generated
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.star
     *
     * @param star the value for site_info.star
     *
     * @mbg.generated
     */
    public void setStar(Integer star) {
        this.star = star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.upda_time
     *
     * @return the value of site_info.upda_time
     *
     * @mbg.generated
     */
    public Date getUpdaTime() {
        return updaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.upda_time
     *
     * @param updaTime the value for site_info.upda_time
     *
     * @mbg.generated
     */
    public void setUpdaTime(Date updaTime) {
        this.updaTime = updaTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.mark
     *
     * @return the value of site_info.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.mark
     *
     * @param mark the value for site_info.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.cf1
     *
     * @return the value of site_info.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.cf1
     *
     * @param cf1 the value for site_info.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1 == null ? null : cf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.cf2
     *
     * @return the value of site_info.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.cf2
     *
     * @param cf2 the value for site_info.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2 == null ? null : cf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column site_info.cf3
     *
     * @return the value of site_info.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column site_info.cf3
     *
     * @param cf3 the value for site_info.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3 == null ? null : cf3.trim();
    }
}