package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_title
 */
@ApiModel(value="cn.tonghua.database.model.TTitle")
public class TTitle extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.title_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="题目id")
    private String titleId;

    /**
     * Database Column Remarks:
     *   题干
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.title_name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="题干")
    private String titleName;

    /**
     * Database Column Remarks:
     *   选项a
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_a
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项a")
    private String optionA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_b
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项b")
    private String optionB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_c
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项c")
    private String optionC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_d
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项d")
    private String optionD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_e
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项e")
    private String optionE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.option_f
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="选项f")
    private String optionF;

    /**
     * Database Column Remarks:
     *   题目类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.titletype_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="题目类型(1:基金,2:理财,3:信用2,4:融资,5:信用,6:股票)")
    private String titletypeId;

    /**
     * Database Column Remarks:
     *   题目难度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.difficult
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="题目难度（01-高，02-中，03-低）")
    private String difficult;

    /**
     * Database Column Remarks:
     *   答题类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.datilx
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="答题类型（01-单选，02-多选）")
    private String datilx;

    /**
     * Database Column Remarks:
     *   答案类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.answerlx
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="答案类型（01-图片，02-文字）")
    private String answerlx;

    /**
     * Database Column Remarks:
     *   答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.answer
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="答案")
    private String answer;

    /**
     * Database Column Remarks:
     *   所属机构号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.org_code
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="orgCode所属机构号")
    private String orgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.upuser
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="upuser")
    private String upuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.uptime
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="uptime")
    private String uptime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.auditor_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="auditorId")
    private String auditorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.audit_option
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="auditOption")
    private String auditOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.audit_status
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="auditStatus")
    private String auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_title.audit_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="auditTime")
    private String auditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.title_id
     *
     * @return the value of t_title.title_id
     *
     * @mbg.generated
     */
    public String getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.title_id
     *
     * @param titleId the value for t_title.title_id
     *
     * @mbg.generated
     */
    public void setTitleId(String titleId) {
        this.titleId = titleId == null ? null : titleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.title_name
     *
     * @return the value of t_title.title_name
     *
     * @mbg.generated
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.title_name
     *
     * @param titleName the value for t_title.title_name
     *
     * @mbg.generated
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName == null ? null : titleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_a
     *
     * @return the value of t_title.option_a
     *
     * @mbg.generated
     */
    public String getOptionA() {
        return optionA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_a
     *
     * @param optionA the value for t_title.option_a
     *
     * @mbg.generated
     */
    public void setOptionA(String optionA) {
        this.optionA = optionA == null ? null : optionA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_b
     *
     * @return the value of t_title.option_b
     *
     * @mbg.generated
     */
    public String getOptionB() {
        return optionB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_b
     *
     * @param optionB the value for t_title.option_b
     *
     * @mbg.generated
     */
    public void setOptionB(String optionB) {
        this.optionB = optionB == null ? null : optionB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_c
     *
     * @return the value of t_title.option_c
     *
     * @mbg.generated
     */
    public String getOptionC() {
        return optionC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_c
     *
     * @param optionC the value for t_title.option_c
     *
     * @mbg.generated
     */
    public void setOptionC(String optionC) {
        this.optionC = optionC == null ? null : optionC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_d
     *
     * @return the value of t_title.option_d
     *
     * @mbg.generated
     */
    public String getOptionD() {
        return optionD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_d
     *
     * @param optionD the value for t_title.option_d
     *
     * @mbg.generated
     */
    public void setOptionD(String optionD) {
        this.optionD = optionD == null ? null : optionD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_e
     *
     * @return the value of t_title.option_e
     *
     * @mbg.generated
     */
    public String getOptionE() {
        return optionE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_e
     *
     * @param optionE the value for t_title.option_e
     *
     * @mbg.generated
     */
    public void setOptionE(String optionE) {
        this.optionE = optionE == null ? null : optionE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.option_f
     *
     * @return the value of t_title.option_f
     *
     * @mbg.generated
     */
    public String getOptionF() {
        return optionF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.option_f
     *
     * @param optionF the value for t_title.option_f
     *
     * @mbg.generated
     */
    public void setOptionF(String optionF) {
        this.optionF = optionF == null ? null : optionF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.titletype_id
     *
     * @return the value of t_title.titletype_id
     *
     * @mbg.generated
     */
    public String getTitletypeId() {
        return titletypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.titletype_id
     *
     * @param titletypeId the value for t_title.titletype_id
     *
     * @mbg.generated
     */
    public void setTitletypeId(String titletypeId) {
        this.titletypeId = titletypeId == null ? null : titletypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.difficult
     *
     * @return the value of t_title.difficult
     *
     * @mbg.generated
     */
    public String getDifficult() {
        return difficult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.difficult
     *
     * @param difficult the value for t_title.difficult
     *
     * @mbg.generated
     */
    public void setDifficult(String difficult) {
        this.difficult = difficult == null ? null : difficult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.datilx
     *
     * @return the value of t_title.datilx
     *
     * @mbg.generated
     */
    public String getDatilx() {
        return datilx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.datilx
     *
     * @param datilx the value for t_title.datilx
     *
     * @mbg.generated
     */
    public void setDatilx(String datilx) {
        this.datilx = datilx == null ? null : datilx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.answerlx
     *
     * @return the value of t_title.answerlx
     *
     * @mbg.generated
     */
    public String getAnswerlx() {
        return answerlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.answerlx
     *
     * @param answerlx the value for t_title.answerlx
     *
     * @mbg.generated
     */
    public void setAnswerlx(String answerlx) {
        this.answerlx = answerlx == null ? null : answerlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.answer
     *
     * @return the value of t_title.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.answer
     *
     * @param answer the value for t_title.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.org_code
     *
     * @return the value of t_title.org_code
     *
     * @mbg.generated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.org_code
     *
     * @param orgCode the value for t_title.org_code
     *
     * @mbg.generated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.upuser
     *
     * @return the value of t_title.upuser
     *
     * @mbg.generated
     */
    public String getUpuser() {
        return upuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.upuser
     *
     * @param upuser the value for t_title.upuser
     *
     * @mbg.generated
     */
    public void setUpuser(String upuser) {
        this.upuser = upuser == null ? null : upuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.uptime
     *
     * @return the value of t_title.uptime
     *
     * @mbg.generated
     */
    public String getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.uptime
     *
     * @param uptime the value for t_title.uptime
     *
     * @mbg.generated
     */
    public void setUptime(String uptime) {
        this.uptime = uptime == null ? null : uptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.auditor_id
     *
     * @return the value of t_title.auditor_id
     *
     * @mbg.generated
     */
    public String getAuditorId() {
        return auditorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.auditor_id
     *
     * @param auditorId the value for t_title.auditor_id
     *
     * @mbg.generated
     */
    public void setAuditorId(String auditorId) {
        this.auditorId = auditorId == null ? null : auditorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.audit_option
     *
     * @return the value of t_title.audit_option
     *
     * @mbg.generated
     */
    public String getAuditOption() {
        return auditOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.audit_option
     *
     * @param auditOption the value for t_title.audit_option
     *
     * @mbg.generated
     */
    public void setAuditOption(String auditOption) {
        this.auditOption = auditOption == null ? null : auditOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.audit_status
     *
     * @return the value of t_title.audit_status
     *
     * @mbg.generated
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.audit_status
     *
     * @param auditStatus the value for t_title.audit_status
     *
     * @mbg.generated
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_title.audit_time
     *
     * @return the value of t_title.audit_time
     *
     * @mbg.generated
     */
    public String getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_title.audit_time
     *
     * @param auditTime the value for t_title.audit_time
     *
     * @mbg.generated
     */
    public void setAuditTime(String auditTime) {
        this.auditTime = auditTime == null ? null : auditTime.trim();
    }
}