package cn.tonghua.database.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserAnswerExample extends cn.tonghua.core.model.AbstractDataAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public UserAnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNull() {
            addCriterion("site_id is null");
            return (Criteria) this;
        }

        public Criteria andSiteIdIsNotNull() {
            addCriterion("site_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiteIdEqualTo(Integer value) {
            addCriterion("site_id =", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotEqualTo(Integer value) {
            addCriterion("site_id <>", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThan(Integer value) {
            addCriterion("site_id >", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("site_id >=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThan(Integer value) {
            addCriterion("site_id <", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdLessThanOrEqualTo(Integer value) {
            addCriterion("site_id <=", value, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdIn(List<Integer> values) {
            addCriterion("site_id in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotIn(List<Integer> values) {
            addCriterion("site_id not in", values, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdBetween(Integer value1, Integer value2) {
            addCriterion("site_id between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andSiteIdNotBetween(Integer value1, Integer value2) {
            addCriterion("site_id not between", value1, value2, "siteId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andMarkIsNull() {
            addCriterion("mark is null");
            return (Criteria) this;
        }

        public Criteria andMarkIsNotNull() {
            addCriterion("mark is not null");
            return (Criteria) this;
        }

        public Criteria andMarkEqualTo(String value) {
            addCriterion("mark =", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotEqualTo(String value) {
            addCriterion("mark <>", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThan(String value) {
            addCriterion("mark >", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkGreaterThanOrEqualTo(String value) {
            addCriterion("mark >=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThan(String value) {
            addCriterion("mark <", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLessThanOrEqualTo(String value) {
            addCriterion("mark <=", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkLike(String value) {
            addCriterion("mark like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotLike(String value) {
            addCriterion("mark not like", value, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkIn(List<String> values) {
            addCriterion("mark in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotIn(List<String> values) {
            addCriterion("mark not in", values, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkBetween(String value1, String value2) {
            addCriterion("mark between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andMarkNotBetween(String value1, String value2) {
            addCriterion("mark not between", value1, value2, "mark");
            return (Criteria) this;
        }

        public Criteria andCf1IsNull() {
            addCriterion("cf1 is null");
            return (Criteria) this;
        }

        public Criteria andCf1IsNotNull() {
            addCriterion("cf1 is not null");
            return (Criteria) this;
        }

        public Criteria andCf1EqualTo(String value) {
            addCriterion("cf1 =", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotEqualTo(String value) {
            addCriterion("cf1 <>", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1GreaterThan(String value) {
            addCriterion("cf1 >", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1GreaterThanOrEqualTo(String value) {
            addCriterion("cf1 >=", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1LessThan(String value) {
            addCriterion("cf1 <", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1LessThanOrEqualTo(String value) {
            addCriterion("cf1 <=", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1Like(String value) {
            addCriterion("cf1 like", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotLike(String value) {
            addCriterion("cf1 not like", value, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1In(List<String> values) {
            addCriterion("cf1 in", values, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotIn(List<String> values) {
            addCriterion("cf1 not in", values, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1Between(String value1, String value2) {
            addCriterion("cf1 between", value1, value2, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf1NotBetween(String value1, String value2) {
            addCriterion("cf1 not between", value1, value2, "cf1");
            return (Criteria) this;
        }

        public Criteria andCf2IsNull() {
            addCriterion("cf2 is null");
            return (Criteria) this;
        }

        public Criteria andCf2IsNotNull() {
            addCriterion("cf2 is not null");
            return (Criteria) this;
        }

        public Criteria andCf2EqualTo(String value) {
            addCriterion("cf2 =", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotEqualTo(String value) {
            addCriterion("cf2 <>", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2GreaterThan(String value) {
            addCriterion("cf2 >", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2GreaterThanOrEqualTo(String value) {
            addCriterion("cf2 >=", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2LessThan(String value) {
            addCriterion("cf2 <", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2LessThanOrEqualTo(String value) {
            addCriterion("cf2 <=", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2Like(String value) {
            addCriterion("cf2 like", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotLike(String value) {
            addCriterion("cf2 not like", value, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2In(List<String> values) {
            addCriterion("cf2 in", values, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotIn(List<String> values) {
            addCriterion("cf2 not in", values, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2Between(String value1, String value2) {
            addCriterion("cf2 between", value1, value2, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf2NotBetween(String value1, String value2) {
            addCriterion("cf2 not between", value1, value2, "cf2");
            return (Criteria) this;
        }

        public Criteria andCf3IsNull() {
            addCriterion("cf3 is null");
            return (Criteria) this;
        }

        public Criteria andCf3IsNotNull() {
            addCriterion("cf3 is not null");
            return (Criteria) this;
        }

        public Criteria andCf3EqualTo(String value) {
            addCriterion("cf3 =", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotEqualTo(String value) {
            addCriterion("cf3 <>", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3GreaterThan(String value) {
            addCriterion("cf3 >", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3GreaterThanOrEqualTo(String value) {
            addCriterion("cf3 >=", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3LessThan(String value) {
            addCriterion("cf3 <", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3LessThanOrEqualTo(String value) {
            addCriterion("cf3 <=", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3Like(String value) {
            addCriterion("cf3 like", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotLike(String value) {
            addCriterion("cf3 not like", value, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3In(List<String> values) {
            addCriterion("cf3 in", values, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotIn(List<String> values) {
            addCriterion("cf3 not in", values, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3Between(String value1, String value2) {
            addCriterion("cf3 between", value1, value2, "cf3");
            return (Criteria) this;
        }

        public Criteria andCf3NotBetween(String value1, String value2) {
            addCriterion("cf3 not between", value1, value2, "cf3");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(Integer value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(Integer value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(Integer value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(Integer value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(Integer value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<Integer> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<Integer> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(Integer value1, Integer value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerId2IsNull() {
            addCriterion("answer_id2 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerId2IsNotNull() {
            addCriterion("answer_id2 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerId2EqualTo(Integer value) {
            addCriterion("answer_id2 =", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2NotEqualTo(Integer value) {
            addCriterion("answer_id2 <>", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2GreaterThan(Integer value) {
            addCriterion("answer_id2 >", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id2 >=", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2LessThan(Integer value) {
            addCriterion("answer_id2 <", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2LessThanOrEqualTo(Integer value) {
            addCriterion("answer_id2 <=", value, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2In(List<Integer> values) {
            addCriterion("answer_id2 in", values, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2NotIn(List<Integer> values) {
            addCriterion("answer_id2 not in", values, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2Between(Integer value1, Integer value2) {
            addCriterion("answer_id2 between", value1, value2, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId2NotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id2 not between", value1, value2, "answerId2");
            return (Criteria) this;
        }

        public Criteria andAnswerId3IsNull() {
            addCriterion("answer_id3 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerId3IsNotNull() {
            addCriterion("answer_id3 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerId3EqualTo(Integer value) {
            addCriterion("answer_id3 =", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3NotEqualTo(Integer value) {
            addCriterion("answer_id3 <>", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3GreaterThan(Integer value) {
            addCriterion("answer_id3 >", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3GreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id3 >=", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3LessThan(Integer value) {
            addCriterion("answer_id3 <", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3LessThanOrEqualTo(Integer value) {
            addCriterion("answer_id3 <=", value, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3In(List<Integer> values) {
            addCriterion("answer_id3 in", values, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3NotIn(List<Integer> values) {
            addCriterion("answer_id3 not in", values, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3Between(Integer value1, Integer value2) {
            addCriterion("answer_id3 between", value1, value2, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId3NotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id3 not between", value1, value2, "answerId3");
            return (Criteria) this;
        }

        public Criteria andAnswerId4IsNull() {
            addCriterion("answer_id4 is null");
            return (Criteria) this;
        }

        public Criteria andAnswerId4IsNotNull() {
            addCriterion("answer_id4 is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerId4EqualTo(Integer value) {
            addCriterion("answer_id4 =", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4NotEqualTo(Integer value) {
            addCriterion("answer_id4 <>", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4GreaterThan(Integer value) {
            addCriterion("answer_id4 >", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4GreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id4 >=", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4LessThan(Integer value) {
            addCriterion("answer_id4 <", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4LessThanOrEqualTo(Integer value) {
            addCriterion("answer_id4 <=", value, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4In(List<Integer> values) {
            addCriterion("answer_id4 in", values, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4NotIn(List<Integer> values) {
            addCriterion("answer_id4 not in", values, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4Between(Integer value1, Integer value2) {
            addCriterion("answer_id4 between", value1, value2, "answerId4");
            return (Criteria) this;
        }

        public Criteria andAnswerId4NotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id4 not between", value1, value2, "answerId4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_answer
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_answer
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}