package cn.tonghua.database.model;

import cn.tonghua.core.model.BaseModel;
import cn.tonghua.database.vo.Severitys;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * Database Table Remarks:
 *   景点信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_answer
 */
@ApiModel(value="cn.tonghua.database.model.UserAnswer")
public class UserAnswer extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="id自增主键")
    private Integer id;

    /**
     * Database Column Remarks:
     *   问题id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.question_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="questionId问题id")
    private Integer questionId;

    /**
     * Database Column Remarks:
     *   景点id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.site_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="siteId景点id")
    private Integer siteId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="createTime创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.mark
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="mark备注")
    private String mark;

    /**
     * Database Column Remarks:
     *   备用1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.cf1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf1备用1")
    private String cf1;

    /**
     * Database Column Remarks:
     *   备用2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.cf2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf2备用2")
    private String cf2;

    /**
     * Database Column Remarks:
     *   备用3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.cf3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="cf3备用3")
    private String cf3;

    /**
     * Database Column Remarks:
     *   答案id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.answer_id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerId答案id")
    @NotNull(message = "答案id不可为空",groups = {Severitys.Insert.class})
    private Integer answerId;

    /**
     * Database Column Remarks:
     *   答案id2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.answer_id2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerId2答案id2")
    private Integer answerId2;

    /**
     * Database Column Remarks:
     *   答案id3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.answer_id3
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerId3答案id3")
    private Integer answerId3;

    /**
     * Database Column Remarks:
     *   答案id4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.answer_id4
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerId4答案id4")
    private Integer answerId4;

    /**
     * Database Column Remarks:
     *   个性化答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_answer.answer_text
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="answerText个性化答案")
    private String answerText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.id
     *
     * @return the value of user_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.id
     *
     * @param id the value for user_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.question_id
     *
     * @return the value of user_answer.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.question_id
     *
     * @param questionId the value for user_answer.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.site_id
     *
     * @return the value of user_answer.site_id
     *
     * @mbg.generated
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.site_id
     *
     * @param siteId the value for user_answer.site_id
     *
     * @mbg.generated
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.create_time
     *
     * @return the value of user_answer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.create_time
     *
     * @param createTime the value for user_answer.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.mark
     *
     * @return the value of user_answer.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.mark
     *
     * @param mark the value for user_answer.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.cf1
     *
     * @return the value of user_answer.cf1
     *
     * @mbg.generated
     */
    public String getCf1() {
        return cf1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.cf1
     *
     * @param cf1 the value for user_answer.cf1
     *
     * @mbg.generated
     */
    public void setCf1(String cf1) {
        this.cf1 = cf1 == null ? null : cf1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.cf2
     *
     * @return the value of user_answer.cf2
     *
     * @mbg.generated
     */
    public String getCf2() {
        return cf2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.cf2
     *
     * @param cf2 the value for user_answer.cf2
     *
     * @mbg.generated
     */
    public void setCf2(String cf2) {
        this.cf2 = cf2 == null ? null : cf2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.cf3
     *
     * @return the value of user_answer.cf3
     *
     * @mbg.generated
     */
    public String getCf3() {
        return cf3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.cf3
     *
     * @param cf3 the value for user_answer.cf3
     *
     * @mbg.generated
     */
    public void setCf3(String cf3) {
        this.cf3 = cf3 == null ? null : cf3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.answer_id
     *
     * @return the value of user_answer.answer_id
     *
     * @mbg.generated
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.answer_id
     *
     * @param answerId the value for user_answer.answer_id
     *
     * @mbg.generated
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.answer_id2
     *
     * @return the value of user_answer.answer_id2
     *
     * @mbg.generated
     */
    public Integer getAnswerId2() {
        return answerId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.answer_id2
     *
     * @param answerId2 the value for user_answer.answer_id2
     *
     * @mbg.generated
     */
    public void setAnswerId2(Integer answerId2) {
        this.answerId2 = answerId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.answer_id3
     *
     * @return the value of user_answer.answer_id3
     *
     * @mbg.generated
     */
    public Integer getAnswerId3() {
        return answerId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.answer_id3
     *
     * @param answerId3 the value for user_answer.answer_id3
     *
     * @mbg.generated
     */
    public void setAnswerId3(Integer answerId3) {
        this.answerId3 = answerId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.answer_id4
     *
     * @return the value of user_answer.answer_id4
     *
     * @mbg.generated
     */
    public Integer getAnswerId4() {
        return answerId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.answer_id4
     *
     * @param answerId4 the value for user_answer.answer_id4
     *
     * @mbg.generated
     */
    public void setAnswerId4(Integer answerId4) {
        this.answerId4 = answerId4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_answer.answer_text
     *
     * @return the value of user_answer.answer_text
     *
     * @mbg.generated
     */
    public String getAnswerText() {
        return answerText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_answer.answer_text
     *
     * @param answerText the value for user_answer.answer_text
     *
     * @mbg.generated
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText == null ? null : answerText.trim();
    }
}