package cn.tonghua.database.mapper;

import cn.tonghua.database.model.SiteQuestion;
import cn.tonghua.database.model.SiteQuestionExample;
import java.util.List;

import cn.tonghua.database.vo.SiteQuestionVO;
import org.apache.ibatis.annotations.Param;

public interface SiteQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    long countByExample(SiteQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int deleteByExample(SiteQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int insert(SiteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int insertSelective(SiteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    List<SiteQuestion> selectByExample(SiteQuestionExample example);

    List<SiteQuestionVO> selectByExampleVO(SiteQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    SiteQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SiteQuestion record, @Param("example") SiteQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SiteQuestion record, @Param("example") SiteQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SiteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SiteQuestion record);
}