package cn.tonghua.database.mapper;

import cn.tonghua.database.model.TTitle;
import cn.tonghua.database.model.TTitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    long countByExample(TTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int deleteByExample(TTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String titleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int insert(TTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int insertSelective(TTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    List<TTitle> selectByExample(TTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    TTitle selectByPrimaryKey(String titleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTitle record, @Param("example") TTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTitle record, @Param("example") TTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_title
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTitle record);
}